from django.contrib import admin
from django.urls import path
from home import views
from .views import place_order_view

urlpatterns = [
    path('', views.index, name="home"),
    path('indexforCustomer', views.indexforCustomer, name="homeforcustomer"),
    path('<str:IPOid>/<str:OrderType>/update_pann/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>', views.Update_pann,name = "OrderDetail_update"),
    path('ChangePassword', views.ChangePassword, name="ChangePassword"),
    path('get-options/', views.get_options, name='get_options'),
    path('<str:IPOid>/<str:OrderType>/IPO_Allotment/<str:group>/<str:IPOType>/<str:InvestType>', views.IPO_Allotment, name='get_options'),
    path('get_pancards/<str:IPOid>/<str:OrderType>/<str:group>/<str:IPOType>/<str:InvestType>', views.get_pancards, name='get_pancards'),
    path('ChangeUserpassword', views.Changepassword, name="ChangeUserpassword"),
    path('IPOSETUP', views.IPOSETUP, name="IPOSETUP"),
    path('ClientSetup', views.ClientSetup, name="ClientSetup"),
    path('ClientSetup/<str:PanNoId>', views.ClientSetup, name="ClientSetup"),
    path('GroupSetup', views.GroupSetup, name="GroupSetup"),
    path('AddCustomerUser', views.AddCustomerUser, name="AddCustomerUser"),
    path('AddIPO', views.AddIPO, name="AddIPO"),
    path('AddClient', views.AddClient, name="AddClient"),
    path('AddGroup', views.AddGroup, name="AddGroup"),
    path('ErrorCSV', views.Error_csv, name="ErrorCSV"),
    path('AddGroup/<str:IPOid>/<str:Action>', views.AddGroupFromPlaceOrder,name="AddGroupFromPlaceOrder"),
    path('edit/<str:IPOid>', views.edit),
    path('EditClient/<str:PanNoId>', views.EditClient),
    path('EditGroup/<str:GroupNameId>', views.EditGroup),
    path('update/<str:IPOid>', views.update),
    path('<str:IPOid>/updatepreopenprice/<str:group>/<str:IPOType>/<str:InvestType>', views.updatepreopenprice),
    path('<str:IPOid>/<str:OrderDetailId>/EditOrderPreOpenPrice/<str:OrderCategory>/<str:InvestorType>/<str:group>/<str:IPOType>/<str:InvestType>', views.EditOrderPreOpenPrice),
    path('UpdateClient/<str:PANNoId>', views.UpdateClient),
    path('UpdateGroup/<str:GroupNameId>', views.UpdateGroup),
    path('delete/<int:IPOid>', views.destroy, name='destroy'),
    path('DeleteClient/<str:PANNoId>', views.DeleteClient),
    path('DeleteAllClient', views.DeleteAllClient),
    path('DeleteGroup/<str:GroupNameId>', views.DeleteGroup),
    path('DeleteOrder/<str:IPOid>/<str:OrderId>/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>', views.DeleteOrder),
    path('<str:IPOid>/SetRate', views.SetRate),
    path('<str:IPOid>/BUY', views.BUY),
    path('BUY/<str:IPOid>/<str:selectgroup>', views.BUY),
    path('<str:IPOid>/SELL', views.sell),
    path('SELL/<str:IPOid>/<str:selectgroup>', views.sell),
    path('<str:IPOid>/Order', views.OrderFunction),
    path('<str:IPOid>/EditOrder/<str:OrderId>/<str:Grpf>/<str:OrCtf>/<str:InTyf>', views.EditOrder),
    path('<str:IPOid>/<str:OrderId>/UpdateOrder/<str:Grpf>/<str:OrCtf>/<str:InTyf>', views.UpdateOrder),
    path('<str:IPOid>/<str:OrderId>/EditOrderRate/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>', views.EditOrderRate),
    path('<str:IPOid>/OrderDetail/<str:Ordtyp>', views.OrderDetailFunction),
    path('<str:IPOid>/OrderDetail/<str:Ordtyp>/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>', views.OrderDetailFunction),
    path('<str:IPOid>/OrderDetail/<str:Ordtyp>/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>', views.OrderDetailFunction),
    path('<str:IPOid>/Order/<str:Groupfilter>/<str:OrderCategoryFilter>/<str:InvestorTypeFilter>',views.filterfromstatus),
    path('<str:IPOid>/<str:OrderType>/AddPan-<str:OrderDetailId>/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.AddPan, name="AddPan"),
    path('<str:IPOid>/<str:OrderType>/FirmAllotment/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>',views.FirmAllotment, name='FirmAllotment'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
    path('autocomplete1', views.autocomplete1, name='autocomplete1'),
    path('<str:IPOid>/Billing', views.Billing, name='Billing'),
    path('<str:IPOid>/Billing/<str:group>/<str:IPOType>/<str:InvestType>', views.FileterBilling, name='Billing'),
    path('<str:IPOid>/download-Billing/<str:group>/<str:IPOType>/<str:InvestorType>',views.exportBillingFilter, name='exportBillingFilter'),
    path('download-Groupwise',views.exportGroupwise, name='exportBillingFilter'),
    path('<str:IPOid>/Sempale-Order',views.Sempale_Order, name='Sempale-Order'),
    path('<str:IPOid>/download-Billing-Pdf/<str:group>/<str:IPOType>/<str:InvestorType>',views.exportBillingFilterpdf, name='exportBillingFilterpdf'),
    path('<str:IPOid>/Backup/',views.Backup, name='Backup'),
    path('AllIpoBackup',views.AllIpoBackup, name='AllIpoBackup'),
    path('<str:IPOid>/download-csv/<str:OrderType>/<str:group>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.export, name='OrderDetail_download'),
    path('<str:IPOid>/Group_wise-download-csv/<str:OrderType>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.Group_wise_export, name='OrderDetail_download'),
    path('<str:IPOid>/Dashboard/<str:value>',views.dashboard, name='Dashboard'),
    path('<str:IPOid>/DashboardForm/<str:value>',views.dashboardform, name='DashboardForm'),
    path('<str:IPOid>/download-AllRecords-csv/<str:OrderType>/<str:group>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.exportall, name='OrderDetail_download_AllRecords'),
    path('<str:IPOid>/Group_wise-download-AllRecords-csv/<str:OrderType>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.Group_wise_exportall, name='OrderDetail_download_AllRecords'),
    path('<str:IPOid>/Status', views.Status, name='Status'),
    path('update-telly-status/', views.update_telly_status, name='update_telly_status'),
    path('GroupWiseDashboard',views.GroupWiseDashboard, name='GroupWiseDashboard'),
    path('BackUp',views.BackUp, name='BackUp'),
    path('panalloted', views.panalloted, name='panalloted'),
    path('<str:IPOid>/<str:OrderType>/upload-csv/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.OrderDetail_upload, name="OrderDetail_upload"),
    path('<str:IPOid>/upload-csv/<str:Groupfilter>/<str:Ordercatagoryfilter>/<str:InvestorTypefilter>',views.Order_upload, name="Order_upload"),
    path('AddPayment', views.AddPayment, name="AddPayment"),
    path('login', views.loginUser, name="login"),
    path('logout', views.logoutUser, name="logout"),
    path('<str:IPOid>/ShareBill',views.GroupBillShare ,name='GroupWiseBillShare'),
    path("accounting/", views.accounting_view, name="accounting"),
    path("get-accounting-entries/", views.get_accounting_entries, name="get_accounting_entries"),
    path("save_transaction/", views.save_transaction, name="save_transaction"),
    path("save_transaction_group/", views.save_transaction_group, name="save_transaction_group"),
    path("add-transaction/", views.add_transaction, name="add_transaction"),
    path("add_transaction_group/", views.add_transaction_group, name="add_transaction_group"),
    path('download-Accounting',views.exportAccountiong, name='exportAccountingFilter'),
    
    path('share-records/',views.Share_AppDetails ,name='Share_AppDetails'),
    path('user-profile/', views.user_profile, name='user_profile'),
    path('update-user-profile/', views.update_user_profile, name='update_user_profile'),
    path("send-telegram-otp/", views.send_telegram_otp, name="send_telegram_otp"),
    path('verify-telegram-otp/', views.verify_telegram_otp, name='verify_telegram_otp'),
    path("place-order/<int:IPOid>/<str:order_type>/", place_order_view, name="place_order"),
    path('share-status-telegram/', views.share_status_telegram, name='share_status_telegram'),
    path('<str:IPOid>/send-status-telegram/', views.send_status_to_telegram, name='send_status_to_telegram'),
    
    path('<str:IPOid>/send-status-telegram/', views.send_status_to_telegram, name='send_status_to_telegram'),
    path('<str:IPOid>/send-status-telegram-image/', views.send_status_to_telegram_image, name='send_status_to_telegram_image'),
    path('delete-accounting-entries/', views.delete_accounting_entries, name='delete_accounting_entries')

]
