# Generated by Django 5.1.1 on 2025-08-26 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_allotment_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Mobileno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='TelegramApi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='TelegramApi_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Telegram_session',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2026, 8, 26, 12, 40, 29, 263752, tzinfo=datetime.timezone.utc)),
        ),
    ]
